name=MemoryCore
version=0.2.0
author=Pooria
maintainer=Pooria <pooria.nekuie@gmail.com>
sentence=A lightweight and reusable SPI NOR Flash library for Winbond W25Qxx devices.
paragraph=MemoryCore is a reusable Arduino library for Winbond W25Qxx SPI NOR Flash memories. It provides a simple and portable API for reading, writing, erasing, JEDEC identification, and device management. Designed for STM32 and other Arduino-compatible platforms with support for shared SPI buses and integration into reusable libraries.
category=Data Storage
url=https://github.com/Pooria-nek/MemoryCore
architectures=*
includes=MemoryCore.h
license=GPL-3.0